const rings = [
  {
    sku: 1,
    title: "Tiffany & Co Somerset Mesh Band",
    effectiveCost: "$166.50",
    ring: 6.75,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Tiffany & Co.",
    src: "./images/ring1.png",
    price30percent: "$216.45",
    salePrice: 225,
  },
  {
    sku: 2,
    title: "Christian Dada Two-Tone Twisted Band Ring",
    effectiveCost: "$127.50",
    ring: 5.5,
    metal: "Gold-Plated, Sterling Silver",
    stone: "-",
    designer: "Christian Dada",
    src: "./images/ring2.png",
    price30percent: "$165.75",
    salePrice: 165,
  },
  {
    sku: 3,
    title: "Ring 14K Pearl Cocktail Ring - Square Setting",
    effectiveCost: "$146.50",
    ring: 5.75,
    metal: "14K Yellow Gold",
    stone: "Pearl",
    designer: "Unknown",
    src: "./images/ring3.png",
    price30percent: "$190.45",
    salePrice: 200,
  },
  {
    sku: 4,
    title: "Ring 14K Pearl Cocktail Ring",
    effectiveCost: "$154.00",
    ring: 5.0,
    metal: "14K Yellow Gold",
    stone: "Pearl",
    designer: "Unknown",
    src: "./images/ring4.png",
    price30percent: "$200.20",
    salePrice: 200,
  },
  {
    sku: 5,
    title: "14K Band Ring",
    effectiveCost: "$135.50",
    ring: 6.75,
    metal: "14K White Gold",
    stone: "-",
    designer: "Unknown",
    src: "./images/ring5.png",
    price30percent: "$176.15",
    salePrice: 175,
  },
  {
    sku: 6,
    title: "Tiffany & Co 1837 Band",
    effectiveCost: "$96.50",
    ring: 5.5,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Tiffany & Co.",
    src: "./images/ring6.png",
    price30percent: "$125.45",
    salePrice: 125,
  },
  {
    sku: 7,
    title: "14K Tourmaline Band",
    effectiveCost: "$206.50",
    ring: 8.0,
    metal: "14K Yellow Gold",
    stone: "Tourmaline",
    designer: "Unknown",
    src: "./images/ring7.png",
    price30percent: "$268.45",
    salePrice: 275,
  },
  {
    sku: 8,
    title: "14k Onyx & Diamond Cocktail Ring",
    effectiveCost: "$206.50",
    ring: 6.5,
    metal: "14K Yellow Gold",
    stone: "Onyx, Diamond",
    designer: "Unknown",
    src: "./images/ring8.png",
    price30percent: "$268.45",
    salePrice: 350,
  },
  {
    sku: 9,
    title: "14K Amethyst & Dyed Jadeite Hololith Band Ring",
    effectiveCost: "$247.75",
    ring: 8.75,
    metal: "14K Yellow Gold",
    stone: "Jade, Amethyst",
    designer: "Unknown",
    src: "./images/ring9.png",
    price30percent: "$322.08",
    salePrice: 275,
  },
  {
    sku: 10,
    title: "14K Loop Band",
    effectiveCost: "$133.75",
    ring: 7.0,
    metal: "14K White Gold",
    stone: "-",
    designer: "Unknown",
    src: "./images/ring10.png",
    price30percent: "$173.88",
    salePrice: 175,
  },
  {
    sku: 11,
    title: "Ring 14K Emerald Band",
    effectiveCost: "$353.50",
    ring: 7.0,
    metal: "14K Yellow Gold",
    stone: "Emerald",
    designer: "Unknown",
    src: "./images/ring11.png",
    price30percent: "$459.55",
    salePrice: 500,
  },
  {
    sku: 12,
    title: "18K Diamond Cocktail Ring",
    effectiveCost: "$236.00",
    ring: 7.0,
    metal: "18K Yellow Gold",
    stone: "Diamond",
    designer: "Unknown",
    src: "./images/ring12.png",
    price30percent: "$306.80",
    salePrice: 300,
  },
  {
    sku: 13,
    title: "Tagliamonte Mother of Pearl Venetion Ring",
    effectiveCost: "$116.00",
    ring: 9.75,
    metal: "Sterling Silver, 18K Yellow Gold ",
    stone: "Venetian Glass, Mother of Pearl",
    designer: "Tagliamonte",
    src: "./images/ring13.png",
    price30percent: "$150.80",
    salePrice: 250,
  },
  {
    sku: 14,
    title: "14K Tourmaline Band",
    effectiveCost: "$101.50",
    ring: 9.75,
    metal: "14K Yellow Gold",
    stone: "Tourmaline Beads",
    designer: "Unknown",
    src: "./images/ring14.png",
    price30percent: "$131.95",
    salePrice: 150,
  },
  {
    sku: 15,
    title: "14K Ruby & Diamond Cocktail Ring",
    effectiveCost: "$94.50",
    ring: 5.5,
    metal: "14K Yellow Gold",
    stone: "Ruby, Diamond",
    designer: "Unknown",
    src: "./images/ring15.png",
    price30percent: "$122.85",
    salePrice: 200,
  },
  {
    sku: 16,
    title: "I. Reiss 14K Prasiolite Cocktail Ring",
    effectiveCost: "$318.62",
    ring: 7.0,
    metal: "14K Yellow Gold",
    stone: "Prasiolite",
    designer: "I. Reiss",
    src: "./images/ring16.png",
    price30percent: "$414.20",
    salePrice: 450,
  },
  {
    sku: 17,
    title: "Pianegonda Smokey Quartz Ring",
    effectiveCost: "$133.62",
    ring: 7.0,
    metal: "Sterling Silver",
    stone: "Quartz",
    designer: "Pianegonda",
    src: "./images/ring17.png",
    price30percent: "$173.70",
    salePrice: 200,
  },
  {
    sku: 18,
    title: "Corneilia Webb Molded Finger Ring",
    effectiveCost: "$67.12",
    ring: 6.5,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Corneilia Webb",
    src: "./images/ring18.png",
    price30percent: "$87.25",
    salePrice: 125,
  },
  {
    sku: 19,
    title: "Jadeite Band",
    effectiveCost: "$52.68",
    ring: 8.0,
    metal: "-",
    stone: "Jade",
    designer: "Unknown",
    src: "./images/ring19.png",
    price30percent: "$68.48",
    salePrice: 65,
  },
  {
    sku: 20,
    title: "Gurhan Citrine Skittle Ring",
    effectiveCost: "$149.58",
    ring: 7.0,
    metal: "Sterling Silver, 24K Yellow Gold",
    stone: "Citrine",
    designer: "Gurhan",
    src: "./images/ring20.png",
    price30percent: "$194.45",
    salePrice: 225,
  },
  {
    sku: 21,
    title: "Gurhan Topaz Band",
    effectiveCost: "$149.58",
    ring: 6.5,
    metal: "Sterling Silver, 22K Yellow Gold",
    stone: "Topaz",
    designer: "Gurhan",
    src: "./images/ring21.png",
    price30percent: "$194.45",
    salePrice: 225,
  },
  {
    sku: 22,
    title: "Gucci Wide Cutout Band",
    effectiveCost: "$129.58",
    ring: 8.5,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Gucci",
    src: "./images/ring22.png",
    price30percent: "$168.45",
    salePrice: 200,
  },
  {
    sku: 23,
    title: "Misa Jewelry 14k Diamond Beak Ring",
    effectiveCost: "$193.58",
    ring: 7.0,
    metal: "14K Yellow Gold",
    stone: "Diamond",
    designer: "Misa",
    src: "./images/ring23.png",
    price30percent: "$251.65",
    salePrice: 250,
  },
  {
    sku: 24,
    title: "Yves Saint Laurent Spiral Ring",
    effectiveCost: "$133.58",
    ring: 8.0,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Yves Saint Laurent",
    src: "./images/ring24.png",
    price30percent: "$173.65",
    salePrice: 175,
  },
  {
    sku: 25,
    title: "Onyx Opal Diamond 10k Gold Ring ",
    effectiveCost: "$252.08",
    ring: 7.25,
    metal: "10K Yellow Gold",
    stone: "Opal, Diamond, Onyx",
    designer: "Unknown",
    src: "./images/ring25.png",
    price30percent: "$327.71",
    salePrice: 300,
  },
  {
    sku: 26,
    title: "Zuni Sterling Silver Turquoise Ring",
    effectiveCost: "$23.04",
    ring: 6.5,
    metal: "Sterling Silver",
    stone: "Turquoise",
    designer: "Unknown",
    src: "./images/ring26.png",
    price30percent: "$29.95",
    salePrice: 30,
  },
  {
    sku: 27,
    title: "Sterling Silver Band Ring",
    effectiveCost: "23.83",
    ring: 6.0,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Unknown",
    src: "./images/ring27.png",
    price30percent: "30.979",
    salePrice: 30,
  },
  {
    sku: 28,
    title: "Baroque Pearl and Sapphire Ring",
    effectiveCost: "331.65",
    ring: 8.0,
    metal: "14K Yellow Gold",
    stone: "Natural Pearl, Sapphire",
    designer: "Unknown",
    src: "./images/ring28.png",
    price30percent: "431.145",
    salePrice: 450,
  },
  {
    sku: 29,
    title: "Silver Fidget Ring",
    effectiveCost: "40",
    ring: 6.5,
    metal: "Sterling Silver",
    stone: "- ",
    designer: "Unknown",
    src: "./images/ring29.png",
    price30percent: "52",
    salePrice: 60,
  },
  {
    sku: 30,
    title: "Mother of Pearl Ring",
    effectiveCost: "21",
    ring: 5.75,
    metal: "Sterling Silver",
    stone: "Mother of Pearl",
    designer: "Unknown",
    src: "./images/ring30.png",
    price30percent: "27.3",
    salePrice: 30,
  },
  {
    sku: 31,
    title: "Georg Jensen",
    effectiveCost: "282.72",
    ring: 5.0,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Georg Jensen",
    src: "./images/ring31.png",
    price30percent: "367.536",
    salePrice: 300,
  },
  {
    sku: 32,
    title: "Tangerine Stone",
    effectiveCost: "32.12",
    ring: 8.5,
    metal: "Sterling Silver",
    stone: "Citrine",
    designer: "Unknown",
    src: "./images/ring32.png",
    price30percent: "41.756",
    salePrice: 50,
  },
  {
    sku: 33,
    title: "Zuni Sterling Silver Turquoise Ring",
    effectiveCost: "106.87",
    ring: 9.5,
    metal: "Sterling Silver",
    stone: "Turquoise",
    designer: "Unknown",
    src: "./images/ring33.png",
    price30percent: "138.931",
    salePrice: 125,
  },
  {
    sku: 34,
    title: "Black and Blue Ring",
    effectiveCost: "60.87",
    ring: 6.75,
    metal: "Sterling Silver",
    stone: "Unknown",
    designer: "Unknown",
    src: "./images/ring34.png",
    price30percent: "79.131",
    salePrice: 55,
  },
  {
    sku: 35,
    title: "Zuni Inlay Sterling Silver",
    effectiveCost: "103.92",
    ring: 7.5,
    metal: "Sterling Silver",
    stone: "Turquoise, Mother of Pearl, Coral, Onyx",
    designer: "Unknown",
    src: "./images/ring35.png",
    price30percent: "135.096",
    salePrice: 125,
  },
  {
    sku: 36,
    title: "Onyx Ring",
    effectiveCost: "0",
    ring: 8.5,
    metal: "Sterling Silver",
    stone: "Onyx",
    designer: "Unknown",
    src: "./images/ring36.png",
    price30percent: "0",
    salePrice: 30,
  },
  {
    sku: 37,
    title: "MOP Ring",
    effectiveCost: "0",
    ring: 9.0,
    metal: "Sterling Silver",
    stone: "Mother of Pearl",
    designer: "Unknown",
    src: "./images/ring37.png",
    price30percent: "0",
    salePrice: 45,
  },
  {
    sku: 38,
    title: "Silver Band",
    effectiveCost: "30",
    ring: 5.5,
    metal: "Sterling Silver",
    stone: "-",
    designer: "Unknown",
    src: "./images/ring38.png",
    price30percent: "39",
    salePrice: 40,
  },
  {
    sku: 39,
    title: "Milky Stone Ring",
    effectiveCost: "0",
    ring: 8.0,
    metal: "Sterling Silver",
    stone: "Unknown",
    designer: "Unknown",
    src: "./images/ring39.png",
    price30percent: "0",
    salePrice: 45,
  },
  {
    sku: 40,
    title: "Silver Ring",
    effectiveCost: "25",
    ring: 5.5,
    metal: "Sterling Silver",
    stone: "Unknown",
    designer: "Unknown",
    src: "./images/ring40.png",
    price30percent: "32.5",
    salePrice: 30,
  },
  {
    sku: 41,
    title: "Amber Stone Ring",
    effectiveCost: "0",
    ring: 8.75,
    metal: "Sterling Silver",
    stone: "Amber",
    designer: "Unknown",
    src: "./images/ring41.png",
    price30percent: "0",
    salePrice: 75,
  },
  {
    sku: 42,
    title: "Coral Ring",
    effectiveCost: "0",
    ring: 8.0,
    metal: "Sterling Silver",
    stone: "Red Coral",
    designer: "Unknown",
    src: "./images/ring42.png",
    price30percent: "0",
    salePrice: 60,
  },
];

export default rings;
